{% set name = "imutils" %}
{% set version = "0.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 857af6169d90e4a0a814130b9b107f5d611150ce440107e1c1233521c6fb1e2b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib
    - numpy
    - opencv
    - scipy

test:
  imports:
    - imutils
    - imutils.face_utils
    - imutils.feature
    - imutils.io
    - imutils.video

about:
  home: "https://github.com/jrosebr1/imutils"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A series of convenience functions to make basic image processing functions such as translation, rotation, resizing, skeletonization, displaying Matplotlib images, sorting contours, detecting edges, and much more easier with OpenCV and both Python 2.7 and Python 3."
  doc_url: "https://github.com/jrosebr1/imutils"
  dev_url: "https://github.com/jrosebr1/imutils"

extra:
  recipe-maintainers:
    - h-vetinari
