travis:
  secure:
    BINSTAR_TOKEN: pz5tIxn7hUmJbbqCNCZBWNN1lCdfHbZ4Gv9S6+xJ6Y+ALEkzrG2l7TS0vnGY51hAEq/+BXKSeFJdxS7/xR6zOrGXUcObE6VEk1/y5VrKR5OQosYfBYeNltO+s6VT2HUnKDEzyVnGCtYkh+kK8SH38Rx1EKRq7ciPbLEhkgCZghDG6Q2v9HW0VKKW2VWwwxOkc/tqGqbdCYRpCBKfletKnKUA8PD4QubR+pGiJLQ+QUDHpwAPFb1PaaqzYr3+J8PpBOu9ZNNMuzcu2Mp3lQofCx2BtnFgNj2xaiRKMqQRELeXZQ+WtuMQyztlawU4xlb16oiOHYb8M3GjVwHA3ht6hhesRJ6sZau7mAlYGgGc+hdbXmI9Pn0REmp/KviTxFf9WFnrTTqpvtDK0777TEXL5o/WF+TmLZmUAHuxTeOrdH2IodQhTLnELJ+zpdUhs31PoIs1nPxqWaF571AyIyXrnwlsvrQ1seTUg5v1TnCu3RfKbsbPkNmt0T4GHxmLkP62FkB3zLa8P1rBu/ESn0sHh5Xy4y4JXLppT8vN5idoZGtdbDQxKxzrqu3jseV/Geu1yQC6X1Ampw7CHe1/c4AHXk9bXi2O05O13dbzvayUzjHWBDeQH1ITp4rojCjRiN51jw4Nl8+Y2Rp0jZMxvr5bBaW6knr0V34HjjQo2ts4gt4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
